const personajes = [
  {"nombre": "Lionel Messi", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Ángel Di María", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Dibu Martínez", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Rodrigo De Paul", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Julián Álvarez", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Paulo Dybala", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Lautaro Martínez", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Enzo Fernández", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Diego Maradona", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Cristiano Ronaldo", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Neymar Jr", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Kylian Mbappé", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Erling Haaland", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Tini Stoessel", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Lali Espósito", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "María Becerra", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Emilia Mernes", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Nicki Nicole", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Duki", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Bizarrap", "categoria": "cantantes", "pista": "Productor musical"},
  {"nombre": "Paulo Londra", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Trueno", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Wos", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Cazzu", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Luck Ra", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "La Joaqui", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "L-Gante", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Tiago PZK", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Lit Killah", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Khea", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Bad Bunny", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Karol G", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Taylor Swift", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Javier Milei", "categoria": "políticos", "pista": "Político"},
  {"nombre": "Cristina Kirchner", "categoria": "políticos", "pista": "Político"},
  {"nombre": "El Papa Francisco", "categoria": "religión", "pista": "Líder religioso"},
  {"nombre": "Goku", "categoria": "anime", "pista": "Personaje de anime"},
  {"nombre": "Naruto", "categoria": "anime", "pista": "Personaje de anime"},
  {"nombre": "Luffy", "categoria": "anime", "pista": "Personaje de anime"},
  {"nombre": "Tanjiro", "categoria": "anime", "pista": "Personaje de anime"},
  {"nombre": "Spider-Man", "categoria": "superhéroes", "pista": "Superhéroe"},
  {"nombre": "Batman", "categoria": "superhéroes", "pista": "Superhéroe"},
  {"nombre": "Homero Simpson", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
  {"nombre": "Bob Esponja", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
  {"nombre": "Pikachu", "categoria": "pokémon", "pista": "Pokémon"},
  {"nombre": "Mario Bros", "categoria": "videojuegos", "pista": "Personaje de videojuego"},
  {"nombre": "Sonic", "categoria": "videojuegos", "pista": "Personaje de videojuego"},
  {"nombre": "El Chavo del 8", "categoria": "series/dibujos", "pista": "Personaje de serie"},
  {"nombre": "Walter White", "categoria": "series", "pista": "Personaje de serie"},
  {"nombre": "Darth Vader", "categoria": "cine", "pista": "Personaje de película"},
  {"nombre": "Joker", "categoria": "cine", "pista": "Villano"},
  {"nombre": "Thanos", "categoria": "cine", "pista": "Villano"},
  {"nombre": "Fernet", "categoria": "bebidas", "pista": "Bebida alcohólica"},
  {"nombre": "Asado", "categoria": "comida", "pista": "Comida argentina"},
  {"nombre": "Milanesa", "categoria": "comida", "pista": "Comida argentina"},
  {"nombre": "Choripán", "categoria": "comida", "pista": "Comida argentina"},
  {"nombre": "Alfajor Havanna", "categoria": "dulces", "pista": "Dulce"},
  {"nombre": "Medialuna", "categoria": "comida", "pista": "Factura"},
  {"nombre": "Mate", "categoria": "bebidas", "pista": "Infusión"},
  {"nombre": "River Plate", "categoria": "fútbol", "pista": "Club de fútbol"},
  {"nombre": "Boca Juniors", "categoria": "fútbol", "pista": "Club de fútbol"},
  {"nombre": "Racing Club", "categoria": "fútbol", "pista": "Club de fútbol"},
  {"nombre": "San Lorenzo", "categoria": "fútbol", "pista": "Club de fútbol"},
  {"nombre": "Independiente", "categoria": "fútbol", "pista": "Club de fútbol"},
  {"nombre": "MrBeast", "categoria": "youtubers", "pista": "Youtuber"},
  {"nombre": "Ibai Llanos", "categoria": "streamers", "pista": "Streamer"},
  {"nombre": "Spreen", "categoria": "streamers", "pista": "Streamer"},
  {"nombre": "Rubius", "categoria": "streamers", "pista": "Streamer"},
  {"nombre": "Mate", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Bombilla", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Termo", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Celular", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Auriculares", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Zapatillas Nike", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Gorra", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Buzo", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Fernet Branca", "categoria": "bebidas", "pista": "bebidas"},
  {"nombre": "Coca Cola", "categoria": "bebidas", "pista": "bebidas"},
  {"nombre": "Alfajor Jorgito", "categoria": "dulces", "pista": "dulces"},
  {"nombre": "Facturas", "categoria": "comida", "pista": "comida"},
  {"nombre": "Milanesa con puré", "categoria": "comida", "pista": "comida"},
  {"nombre": "Asado", "categoria": "comida", "pista": "comida"},
  {"nombre": "Choripán", "categoria": "comida", "pista": "comida"},
  {"nombre": "Sube", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Colectivo", "categoria": "transporte", "pista": "transporte"},
  {"nombre": "Remera de Boca", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Remera de River", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Vape", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Pava eléctrica", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Pochoclos", "categoria": "comida", "pista": "comida"},
  {"nombre": "Pizza con fainá", "categoria": "comida", "pista": "comida"},
  {"nombre": "Argentina", "categoria": "países", "pista": "países"},
  {"nombre": "Brasil", "categoria": "países", "pista": "países"},
  {"nombre": "Uruguay", "categoria": "países", "pista": "países"},
  {"nombre": "Paraguay", "categoria": "países", "pista": "países"},
  {"nombre": "Chile", "categoria": "países", "pista": "países"},
  {"nombre": "España", "categoria": "países", "pista": "países"},
  {"nombre": "Italia", "categoria": "países", "pista": "países"},
  {"nombre": "Francia", "categoria": "países", "pista": "países"},
  {"nombre": "Estados Unidos", "categoria": "países", "pista": "países"},
  {"nombre": "México", "categoria": "países", "pista": "países"},
  {"nombre": "Japón", "categoria": "países", "pista": "países"},
  {"nombre": "Corea del Sur", "categoria": "países", "pista": "países"},
  {"nombre": "Alemania", "categoria": "países", "pista": "países"},
  {"nombre": "Inglaterra", "categoria": "países", "pista": "países"},
  {"nombre": "Portugal", "categoria": "países", "pista": "países"},
  {"nombre": "Colombia", "categoria": "países", "pista": "países"},
  {"nombre": "Perú", "categoria": "países", "pista": "países"},
  {"nombre": "Qatar", "categoria": "países", "pista": "países"},
  {"nombre": "Arabia Saudita", "categoria": "países", "pista": "países"},
  {"nombre": "Manu Ginóbili", "categoria": "deportistas", "pista": "Deportista"},
{"nombre": "Juan Martín del Potro", "categoria": "deportistas", "pista": "Deportista"},
{"nombre": "Gabriela Sabatini", "categoria": "deportistas", "pista": "Deportista"},
{"nombre": "Luis Scola", "categoria": "deportistas", "pista": "Deportista"},
{"nombre": "Carlos Tevez", "categoria": "deportistas", "pista": "Futbolista"},
{"nombre": "Sergio Agüero", "categoria": "deportistas", "pista": "Futbolista"},
{"nombre": "Gabriela Sabatini", "categoria": "deportistas", "pista": "Deportista"},
{"nombre": "Luciano Aued", "categoria": "deportistas", "pista": "Deportista"},
{"nombre": "Facundo Campazzo", "categoria": "deportistas", "pista": "Deportista"},
{"nombre": "Paula Pareto", "categoria": "deportistas", "pista": "Deportista"},{"nombre": "Abel Pintos", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Soledad Pastorutti", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Rusherking", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "FMK", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Big One", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Quevedo", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Feid", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Shakira", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Peso Pluma", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Rihanna", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Empanadas", "categoria": "comida", "pista": "Comida"},
{"nombre": "Locro", "categoria": "comida", "pista": "Comida"},
{"nombre": "Dulce de leche", "categoria": "dulces", "pista": "Dulce"},
{"nombre": "Cerveza Quilmes", "categoria": "bebidas", "pista": "Bebida"},
{"nombre": "Vino Malbec", "categoria": "bebidas", "pista": "Bebida"},
{"nombre": "Gancia", "categoria": "bebidas", "pista": "Bebida"},
{"nombre": "Bolivia", "categoria": "países", "pista": "País"},
{"nombre": "Ecuador", "categoria": "países", "pista": "País"},
{"nombre": "Venezuela", "categoria": "países", "pista": "País"},
{"nombre": "Canadá", "categoria": "países", "pista": "País"},
{"nombre": "Rusia", "categoria": "países", "pista": "País"},
{"nombre": "China", "categoria": "países", "pista": "País"},
{"nombre": "Estudiantes de La Plata", "categoria": "fútbol", "pista": "Club de fútbol"},
{"nombre": "Newell's Old Boys", "categoria": "fútbol", "pista": "Club de fútbol"},
{"nombre": "Vélez Sarsfield", "categoria": "fútbol", "pista": "Club de fútbol"},
{"nombre": "Rosario Central", "categoria": "fútbol", "pista": "Club de fútbol"},
{"nombre": "DNI", "categoria": "objetos", "pista": "objetos"},
{"nombre": "Bandera argentina", "categoria": "objetos", "pista": "objetos"},
{"nombre": "Botines de fútbol", "categoria": "objetos", "pista": "objetos"},
{"nombre": "Cuaderno", "categoria": "objetos", "pista": "objetos"},
{"nombre": "Bart Simpson", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Shrek", "categoria": "series/dibujos", "pista": "Personaje de película"},
{"nombre": "Ricardo Darín", "categoria": "actores", "pista": "Actor"},
{"nombre": "Guillermo Francella", "categoria": "actores", "pista": "Actor"},
{"nombre": "China Suárez", "categoria": "actores", "pista": "Actriz"},
{"nombre": "Leonardo DiCaprio", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Tony Stark (Iron Man)", "categoria": "superhéroes", "pista": "Personaje de película"},
{"nombre": "Tyrion Lannister (enano de Game of Trhones)", "categoria": "series", "pista": "Personaje de serie"},
{"nombre": "Eleven (Stranger Things)", "categoria": "series", "pista": "Personaje de serie"},
{"nombre": "Tony Soprano (Los Soprano)", "categoria": "series", "pista": "Personaje de serie"},
{"nombre": "Harry Potter", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "DNI", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Llaves", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Billetera", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Mochila", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Cuaderno Rivadavia", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Lápiz", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Goma de borrar", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Reloj", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Anteojos", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Cargador de celular", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Control remoto", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Llave inglesa", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Botella de agua", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Paraguas", "categoria": "objetos", "pista": "Objeto"},
{"nombre": "Scooby Doo", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Shaggy", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Fred", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Velma", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Daphne", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Tom", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Jerry", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Bugs Bunny", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Pato Lucas", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Porky Pig", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Bombón", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Burbuja", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Bellota", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Dexter", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Coraje", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Johnny Bravo", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
{"nombre": "Ace Ventura", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "La Máscara", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Forrest Gump", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Neo (Matrix)", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Jack Sparrow (Piratas del Caribe)", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Fiona", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Burro de Shrek", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Wilson (pelota Naufrago)", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Willy Wonka", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Harry Potter", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Hermione Granger (Harry Potter)", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Ron Weasley (Harry Potter)", "categoria": "cine", "pista": "Personaje de película"},
{"nombre": "Guido Süller", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Silvia Süller", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Moria Casán", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Jorge Rial", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Luis Ventura", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Marcelo Polino", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Carmen Barbieri", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Santiago Bal", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Florencia Peña", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Cinthia Fernández", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Noelia Pompa", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Silvina Escudero", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Ricardo Fort", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Anamá Ferreyra", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Lizy Tagliani", "categoria": "famosos", "pista": "Personaje de TV"}, // empezó a pegar fuerte en esa época
{"nombre": "Pampita", "categoria": "famosos", "pista": "Personaje de TV"},
{"nombre": "Flavio Mendoza", "categoria": "famosos", "pista": "Personaje de TV"},{"nombre": "Buenos Aires", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Córdoba", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Rosario", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Mendoza", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Mar del Plata", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Bariloche", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Salta", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Ushuaia", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Nueva York", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "París", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Londres", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Roma", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Madrid", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Barcelona", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Tokio", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Dubái", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Miami", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Los Ángeles", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Las Vegas", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Río de Janeiro", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Santiago de Chile", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Montevideo", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Bogotá", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Lima", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Berlin", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Ámsterdam", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Moscú", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Sidney", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Cancún", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Punta del Este", "categoria": "ciudades", "pista": "Ciudad"},
{"nombre": "Nike", "categoria": "marcas", "pista": "Marca"},
{"nombre": "Adidas", "categoria": "marcas", "pista": "Marca"},
{"nombre": "Coca Cola", "categoria": "marcas", "pista": "Marca"},
{"nombre": "Pepsi", "categoria": "marcas", "pista": "Marca"},
{"nombre": "Apple", "categoria": "marcas", "pista": "Marca"},
{"nombre": "Samsung", "categoria": "marcas", "pista": "Marca"},
{"nombre": "McDonald's", "categoria": "marcas", "pista": "Marca"},
{"nombre": "Burger King", "categoria": "marcas", "pista": "Marca"},
{"nombre": "Havanna", "categoria": "marcas", "pista": "Marca"},
{"nombre": "Lucchetti", "categoria": "marcas", "pista": "Marca"},
{"nombre": "Arcor", "categoria": "marcas", "pista": "Marca"},
{"nombre": "Perro", "categoria": "animales", "pista": "Animal"},
{"nombre": "Gato", "categoria": "animales", "pista": "Animal"},
{"nombre": "León", "categoria": "animales", "pista": "Animal"},
{"nombre": "Elefante", "categoria": "animales", "pista": "Animal"},
{"nombre": "Tigre", "categoria": "animales", "pista": "Animal"},
{"nombre": "Oso", "categoria": "animales", "pista": "Animal"},
{"nombre": "Pingüino", "categoria": "animales", "pista": "Animal"},
{"nombre": "Delfín", "categoria": "animales", "pista": "Animal"},
{"nombre": "Caballo", "categoria": "animales", "pista": "Animal"},
{"nombre": "Vaca", "categoria": "animales", "pista": "Animal"},{"nombre": "Médico", "categoria": "profesiones", "pista": "Profesión"},
{"nombre": "Profesor", "categoria": "profesiones", "pista": "Profesión"},
{"nombre": "Policía", "categoria": "profesiones", "pista": "Profesión"},
{"nombre": "Bombero", "categoria": "profesiones", "pista": "Profesión"},
{"nombre": "Abogado", "categoria": "profesiones", "pista": "Profesión"},
{"nombre": "Cocinero", "categoria": "profesiones", "pista": "Profesión"},
{"nombre": "Programador", "categoria": "profesiones", "pista": "Profesión"},
{"nombre": "Periodista", "categoria": "profesiones", "pista": "Profesión"},
{"nombre": "Arquitecto", "categoria": "profesiones", "pista": "Profesión"},
{"nombre": "Instagram", "categoria": "apps", "pista": "App"},
{"nombre": "TikTok", "categoria": "apps", "pista": "App"},
{"nombre": "WhatsApp", "categoria": "apps", "pista": "App"},
{"nombre": "YouTube", "categoria": "apps", "pista": "App"},
{"nombre": "Twitter", "categoria": "apps", "pista": "App"},
{"nombre": "Spotify", "categoria": "apps", "pista": "App"},
{"nombre": "Netflix", "categoria": "apps", "pista": "App"},
{"nombre": "Mercado Libre", "categoria": "apps", "pista": "App"},
{"nombre": "Guitarra", "categoria": "instrumentos", "pista": "Instrumento"},
{"nombre": "Batería", "categoria": "instrumentos", "pista": "Instrumento"},
{"nombre": "Piano", "categoria": "instrumentos", "pista": "Instrumento"},
{"nombre": "Bajo", "categoria": "instrumentos", "pista": "Instrumento"},
{"nombre": "Bombos legüeros", "categoria": "instrumentos", "pista": "Instrumento"},
{"nombre": "Manzana", "categoria": "frutas", "pista": "Fruta"},
{"nombre": "Banana", "categoria": "frutas", "pista": "Fruta"},
{"nombre": "Naranja", "categoria": "frutas", "pista": "Fruta"},
{"nombre": "Limón", "categoria": "frutas", "pista": "Fruta"},
{"nombre": "Frutilla", "categoria": "frutas", "pista": "Fruta"},
{"nombre": "Sandía", "categoria": "frutas", "pista": "Fruta"},
{"nombre": "Tomate", "categoria": "verduras", "pista": "Verdura"},
{"nombre": "Lechuga", "categoria": "verduras", "pista": "Verdura"},
{"nombre": "Papa", "categoria": "verduras", "pista": "Verdura"},
{"nombre": "Zanahoria", "categoria": "verduras", "pista": "Verdura"},
{"nombre": "Cebolla", "categoria": "verduras", "pista": "Verdura"},
{"nombre": "Rojo", "categoria": "colores", "pista": "Color"},
{"nombre": "Azul", "categoria": "colores", "pista": "Color"},
{"nombre": "Verde", "categoria": "colores", "pista": "Color"},
{"nombre": "Amarillo", "categoria": "colores", "pista": "Color"},
{"nombre": "Negro", "categoria": "colores", "pista": "Color"},
{"nombre": "Blanco", "categoria": "colores", "pista": "Color"},
{"nombre": "Violeta", "categoria": "colores", "pista": "Color"},
{"nombre": "Rosa", "categoria": "colores", "pista": "Color"},
{"nombre": "Celeste", "categoria": "colores", "pista": "Color"},
{"nombre": "Fútbol", "categoria": "deportes", "pista": "Deporte"},
{"nombre": "Tenis", "categoria": "deportes", "pista": "Deporte"},
{"nombre": "Básquet", "categoria": "deportes", "pista": "Deporte"},
{"nombre": "Vóley", "categoria": "deportes", "pista": "Deporte"},
{"nombre": "Rugby", "categoria": "deportes", "pista": "Deporte"},
{"nombre": "Hockey", "categoria": "deportes", "pista": "Deporte"},
{"nombre": "Natación", "categoria": "deportes", "pista": "Deporte"},
{"nombre": "Boxeo", "categoria": "deportes", "pista": "Deporte"},
{"nombre": "Moni Argento", "categoria": "series", "pista": "Personaje de serie"},
{"nombre": "Pepe Argento", "categoria": "series", "pista": "Personaje de serie"},
{"nombre": "Alfajor Jorgito", "categoria": "golosinas", "pista": "Golosina"},
{"nombre": "Block", "categoria": "golosinas", "pista": "Golosina"},
{"nombre": "Sugus", "categoria": "golosinas", "pista": "Golosina"},
{"nombre": "Mogul", "categoria": "golosinas", "pista": "Golosina"},
{"nombre": "Paleta Pico Dulce", "categoria": "golosinas", "pista": "Golosina"},
{"nombre": "Rocklets", "categoria": "golosinas", "pista": "Golosina"},
{"nombre": "Mentoplus", "categoria": "golosinas", "pista": "Golosina"},
{"nombre": "Flynn Paff", "categoria": "golosinas", "pista": "Golosina"},
{"nombre": "Gustavo Cerati", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Indio Solari", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Andrés Ciro Martínez", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Ricardo Mollo", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Vicentico", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Pity Álvarez", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "John Lennon", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Paul McCartney", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Mick Jagger", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Freddie Mercury", "categoria": "cantantes", "pista": "Cantante"},
{"nombre": "Axl Rose", "categoria": "cantantes", "pista": "Cantante"}
]
