const personajes = [
  {"nombre": "Lionel Messi", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Ángel Di María", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Dibu Martínez", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Rodrigo De Paul", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Julián Álvarez", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Paulo Dybala", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Lautaro Martínez", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Enzo Fernández", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Diego Maradona", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Cristiano Ronaldo", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Neymar Jr", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Kylian Mbappé", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Erling Haaland", "categoria": "deportistas", "pista": "Futbolista"},
  {"nombre": "Tini Stoessel", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Lali Espósito", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "María Becerra", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Emilia Mernes", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Nicki Nicole", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Duki", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Bizarrap", "categoria": "cantantes", "pista": "Productor musical"},
  {"nombre": "Paulo Londra", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Trueno", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Wos", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Cazzu", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Luck Ra", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "La Joaqui", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "L-Gante", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Tiago PZK", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Lit Killah", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Khea", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Bad Bunny", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Karol G", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Taylor Swift", "categoria": "cantantes", "pista": "Cantante"},
  {"nombre": "Javier Milei", "categoria": "políticos", "pista": "Político"},
  {"nombre": "Cristina Kirchner", "categoria": "políticos", "pista": "Político"},
  {"nombre": "El Papa Francisco", "categoria": "religión", "pista": "Líder religioso"},
  {"nombre": "Goku", "categoria": "anime", "pista": "Personaje de anime"},
  {"nombre": "Naruto", "categoria": "anime", "pista": "Personaje de anime"},
  {"nombre": "Luffy", "categoria": "anime", "pista": "Personaje de anime"},
  {"nombre": "Tanjiro", "categoria": "anime", "pista": "Personaje de anime"},
  {"nombre": "Spider-Man", "categoria": "superhéroes", "pista": "Superhéroe"},
  {"nombre": "Batman", "categoria": "superhéroes", "pista": "Superhéroe"},
  {"nombre": "Homero Simpson", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
  {"nombre": "Bob Esponja", "categoria": "series/dibujos", "pista": "Personaje de dibujos"},
  {"nombre": "Pikachu", "categoria": "pokémon", "pista": "Pokémon"},
  {"nombre": "Mario Bros", "categoria": "videojuegos", "pista": "Personaje de videojuego"},
  {"nombre": "Sonic", "categoria": "videojuegos", "pista": "Personaje de videojuego"},
  {"nombre": "El Chavo del 8", "categoria": "series/dibujos", "pista": "Personaje de serie"},
  {"nombre": "Walter White", "categoria": "series", "pista": "Personaje de serie"},
  {"nombre": "Darth Vader", "categoria": "cine", "pista": "Personaje de película"},
  {"nombre": "Joker", "categoria": "cine", "pista": "Villano"},
  {"nombre": "Thanos", "categoria": "cine", "pista": "Villano"},
  {"nombre": "Fernet", "categoria": "bebidas", "pista": "Bebida alcohólica"},
  {"nombre": "Asado", "categoria": "comida", "pista": "Comida argentina"},
  {"nombre": "Milanesa", "categoria": "comida", "pista": "Comida argentina"},
  {"nombre": "Choripán", "categoria": "comida", "pista": "Comida argentina"},
  {"nombre": "Alfajor Havanna", "categoria": "dulces", "pista": "Dulce"},
  {"nombre": "Medialuna", "categoria": "comida", "pista": "Factura"},
  {"nombre": "Mate", "categoria": "bebidas", "pista": "Infusión"},
  {"nombre": "River Plate", "categoria": "fútbol", "pista": "Club de fútbol"},
  {"nombre": "Boca Juniors", "categoria": "fútbol", "pista": "Club de fútbol"},
  {"nombre": "Racing Club", "categoria": "fútbol", "pista": "Club de fútbol"},
  {"nombre": "San Lorenzo", "categoria": "fútbol", "pista": "Club de fútbol"},
  {"nombre": "Independiente", "categoria": "fútbol", "pista": "Club de fútbol"},
  {"nombre": "MrBeast", "categoria": "youtubers", "pista": "Youtuber"},
  {"nombre": "Ibai Llanos", "categoria": "streamers", "pista": "Streamer"},
  {"nombre": "Spreen", "categoria": "streamers", "pista": "Streamer"},
  {"nombre": "Rubius", "categoria": "streamers", "pista": "Streamer"},
  {"nombre": "Mate", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Bombilla", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Termo Stanley", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Celular", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Auriculares", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Zapatillas Nike", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Gorra", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Buzo Oversize", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Fernet Branca", "categoria": "bebidas", "pista": "bebidas"},
  {"nombre": "Coca Cola", "categoria": "bebidas", "pista": "bebidas"},
  {"nombre": "Alfajor Jorgito", "categoria": "dulces", "pista": "dulces"},
  {"nombre": "Facturas", "categoria": "comida", "pista": "comida"},
  {"nombre": "Milanesa con puré", "categoria": "comida", "pista": "comida"},
  {"nombre": "Asado", "categoria": "comida", "pista": "comida"},
  {"nombre": "Choripán", "categoria": "comida", "pista": "comida"},
  {"nombre": "Sube", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Colectivo", "categoria": "transporte", "pista": "transporte"},
  {"nombre": "Remera de Boca", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Remera de River", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Vape", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Pava eléctrica", "categoria": "objetos", "pista": "objetos"},
  {"nombre": "Pochoclos", "categoria": "comida", "pista": "comida"},
  {"nombre": "Pizza con fainá", "categoria": "comida", "pista": "comida"},
  {"nombre": "Argentina", "categoria": "países", "pista": "países"},
  {"nombre": "Brasil", "categoria": "países", "pista": "países"},
  {"nombre": "Uruguay", "categoria": "países", "pista": "países"},
  {"nombre": "Paraguay", "categoria": "países", "pista": "países"},
  {"nombre": "Chile", "categoria": "países", "pista": "países"},
  {"nombre": "España", "categoria": "países", "pista": "países"},
  {"nombre": "Italia", "categoria": "países", "pista": "países"},
  {"nombre": "Francia", "categoria": "países", "pista": "países"},
  {"nombre": "Estados Unidos", "categoria": "países", "pista": "países"},
  {"nombre": "México", "categoria": "países", "pista": "países"},
  {"nombre": "Japón", "categoria": "países", "pista": "países"},
  {"nombre": "Corea del Sur", "categoria": "países", "pista": "países"},
  {"nombre": "Alemania", "categoria": "países", "pista": "países"},
  {"nombre": "Inglaterra", "categoria": "países", "pista": "países"},
  {"nombre": "Portugal", "categoria": "países", "pista": "países"},
  {"nombre": "Colombia", "categoria": "países", "pista": "países"},
  {"nombre": "Perú", "categoria": "países", "pista": "países"},
  {"nombre": "Qatar", "categoria": "países", "pista": "países"},
  {"nombre": "Arabia Saudita", "categoria": "países", "pista": "países"}
]